name: handz
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rxdart: ^0.27.1
  image_picker: ^0.8.7+4
  dio: 5.1.1
  connectivity_plus: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  #flutter_launcher_icons: ^0.13.1

  #flutter_launcher_icons:
  # image_path: "assets/images/ic_logo.png"
  # image_path_android: "assets/images/ic_logo.png"
  # android: true
  # ios: true
  # min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
         - asset: assets/fonts/Poppins-Regular.ttf

